### ISSUE TITLE
Unable to read cdf files

### ISSUE THREAD

**Issue by sasi143** [PyMassSpec/PyMassSpec#17]
I am not able to read my "cdf" files using this library. somehow the cdf files are working fine if I am taking from "pyms-data" data folder

**Comment by domdfcoding** [comment]
Hi @sasi143, thank you for opening this issue and I'm sorry you've encountered this. 

If you could send me one of the files you are having trouble with and any error messages you encounter I'll try and work out why it isn't working.

I think you can attach the file to this issue. If not send it to me by email; my contact info is on my GitHub profile.

Thanks
